# -*- coding: utf-8 -*-
"""
Created on Fri Jan 30 14:24:06 2026

@author: sucre
"""

def add_reki_teacher(file_path, manifestation):
    manifestation.append(" I meet and learn from a skilled raykee teacher ")
    manifestation.append(" I find a skilled raykee teacher ")
    manifestation.append(" A skilled raykee teacher finds me ")
    manifestation.append(" A skilled raykee teacher desires to teach me ")
    manifestation.append(" A skilled raykee teacher seeks me out to be a student ")
    manifestation.append(" I study with a skilled raykee teacher ")
    manifestation.append(" I practice with a skilled raykee teacher ")
    manifestation.append(" I learn much from a skilled raykee teacher ")
    manifestation.append(" I learn quickly from a skilled raykee teacher ")
    manifestation.append(" I meet and become friends with a skilled raykee teacher ")
    file_path.append('r_meditation.manifestation.coaching.txt')

def add_chi_capabilities(file_path, manifestation):
    manifestation.append(" I have mastered my chee energy and use it like a master of sheenanjoo ")
    manifestation.append(" I control and direct my chee energy ")
    manifestation.append(" I constantly learn new ways to control and direct my chee energy ")
    manifestation.append(" I constantly learn more about chee energy ")
    manifestation.append(" I constantly learn more about how to direct and control chee energy ")
    manifestation.append(" my chee energy flows freely and perfectly ")
    manifestation.append(" my chee energy flows freely and powerfully ")
    manifestation.append(" my chee energy flows quickly and easily ")
    manifestation.append(" I can use my chee energy to become invisible ")
    manifestation.append(" I can use my chee energy to heal myself ")
    manifestation.append(" I use my chee energy to heal myself ")
    manifestation.append(" I observe my chee energy ")
    manifestation.append(" I notice my chee energy ")
    manifestation.append(" I learn from my chee energy ")
    manifestation.append(" I observe my chee energy every day ")
    manifestation.append(" I notice my chee energy every day ")
    manifestation.append(" I learn from my chee energy every day ")
    manifestation.append(" I can use my chee energy to heal myself and others ")
    manifestation.append(" I can use my chee energy to empower all my senses and awareness ")
    manifestation.append(" I can use my chee energy to become fast and quick ")
    manifestation.append(" I can use my chee energy to become faster than human ")
    manifestation.append(" I can use my chee energy to be stronger than my body ")
    manifestation.append(" I can use my chee energy to empower my strength ")
    manifestation.append(" I can use my chee energy to empower my dexterity ")
    manifestation.append(" I can use my chee energy to empower my constitution ")
    manifestation.append(" I can use my chee energy to empower my wisdom ")
    manifestation.append(" I can use my chee energy to empower my intelligence ")
    manifestation.append(" I can use my chee energy to empower my charisma ")
    manifestation.append(" I can use my chee energy to empower my communication ")
    manifestation.append(" I can use my chee energy to empower my attractiveness ")
    manifestation.append(" I can use my chee energy to empower my physical senses ")
    manifestation.append(" I can use my chee energy to empower my psychic senses ")
    manifestation.append(" I can use my chee energy to empower my spiritual senses ")
    manifestation.append(" I can use my chee energy to empower my physical awareness ")
    manifestation.append(" I can use my chee energy to empower my psychic awareness ")
    manifestation.append(" I can use my chee energy to empower my spiritual awareness ")
    manifestation.append(" I can use my chee energy to heal myself and others ")
    manifestation.append(" I use my chee energy to empower all my senses and awareness ")
    manifestation.append(" I use my chee energy to become fast and quick ")
    manifestation.append(" I use my chee energy to become faster than human ")
    manifestation.append(" I use my chee energy to be stronger than my body ")
    manifestation.append(" I use my chee energy to empower my strength ")
    manifestation.append(" I use my chee energy to empower my dexterity ")
    manifestation.append(" I use my chee energy to empower my constitution ")
    manifestation.append(" I use my chee energy to empower my wisdom ")
    manifestation.append(" I use my chee energy to empower my intelligence ")
    manifestation.append(" I use my chee energy to empower my charisma ")
    manifestation.append(" I use my chee energy to empower my communication ")
    manifestation.append(" I use my chee energy to empower my attractiveness ")
    manifestation.append(" I use my chee energy to empower my physical senses ")
    manifestation.append(" I use my chee energy to empower my psychic senses ")
    manifestation.append(" I use my chee energy to empower my spiritual senses ")
    manifestation.append(" I use my chee energy to empower my physical awareness ")
    manifestation.append(" I use my chee energy to empower my psychic awareness ")
    manifestation.append(" I use my chee energy to empower my spiritual awareness ")
    manifestation.append(" I have unlocked the full capabilities of using my chee energy ")
    manifestation.append(" I have unleashed the full capabilities of using my chee energy ")
    manifestation.append(" I unleash the full capabilities of my chee energy ")
    manifestation.append(" I unlock the full capabilities of my chee energy ")
    manifestation.append(" I use my chee energy to empower my movements and actions ")
    file_path.append('r_meditation.manifestation.coaching.txt')


def add_leverage_chemistry_study(file_path, pain_leverage_statements, pleasure_leverage_statements):
    pain_leverage_statements.append(" skipping my chemistry study and practice ")
    pain_leverage_statements.append(" missing my chemistry classes ")
    pain_leverage_statements.append(" skipping my chemistry study ")
    pain_leverage_statements.append(" procrastinating on my chemistry studies ")
    file_path.append('dickens_leverage_pain.txt')
    
    pleasure_leverage_statements.append(" I learn more chemistry concepts and knowledge ")
    pleasure_leverage_statements.append(" I apply chemistry concepts and knowledge in everyday life ")
    pleasure_leverage_statements.append(" I learn and use chemistry concepts ")
    pleasure_leverage_statements.append(" I learn and use chemistry knowledge ")
    pleasure_leverage_statements.append(" I increase my chemistry knowledge ")
    pleasure_leverage_statements.append(" I gain more chemistry knowledge ")
    pleasure_leverage_statements.append(" I feel good gaining more chemistry knowledge ")
    pleasure_leverage_statements.append(" I feel good gaining more chemistry experience ")
    pleasure_leverage_statements.append(" I acquire and use more chemistry knowledge ")
    pleasure_leverage_statements.append(" I improve my chemistry and alchemical knowledge ")
    pleasure_leverage_statements.append(" I think in terms of chemistry and alchemical knowledge ")
    file_path.append('dickens_leverage_pleasure.txt')

def add_dream_job(manifestation):
    manifestation.append(" I associate to why I want my dream job ")
    manifestation.append(" I associate to why I desire my dream job ")
    manifestation.append(" I visualize myself having my dream job ")
    manifestation.append(" I visualize myself doing my dream job ")
    manifestation.append(" I vividly see visualize myself having my dream job ")
    manifestation.append(" I vividly see  myself doing my dream job ")
    manifestation.append(" I envision myself having my dream job ")
    manifestation.append(" I clearly see myself having my dream job ")
    manifestation.append(" I know I have my dream job ")
    manifestation.append(" I release all resistance between me and my dream job ")
    manifestation.append(" I believe I have my dream job ")
    manifestation.append(" I already have my dream job ")
    manifestation.append(" I ask for my dream job ")
    manifestation.append(" I act to create my dream job ")
    manifestation.append(" I work to create my dream job ")
    manifestation.append(" I build my dream job ")
    manifestation.append(" I allow my dream job into my life ")
    manifestation.append(" I accept my dream job " )
    manifestation.append(" I have my dream job and I love it more every workday ")
    manifestation.append(" I feel liberated because I earn great money from my dream job ")
    manifestation.append(" I feel great relief that I earn great money from my dream job ")
    manifestation.append(" I feel pride in the skill I demonstrate at my dream job ")
    manifestation.append(" I am the star employee at my dream job ")
    manifestation.append(" I am full of joy that my dream job has found me ")
    manifestation.append(" I feel tremendous optimism before during and after working at my dream job ")
    manifestation.append(" I feel peaceful when I realize I have my dream job ")
    manifestation.append(" I feel glad because I have my dream job ")
    manifestation.append(" I feel grateful when I realize I have my dream job ")
    manifestation.append(" I feel grateful because I have my dream job ")
    manifestation.append(" I feel passionate at my dream job ")


